const products = [
  {
    shouldDesign: true,
    types: [
      "wallet_coins_darkBrown_front_SUB",
      "wallet_coins_darkBrown_inside_SUB",
    ],
    multiDesign: true,
    designImage: {
      desktop: "",
      mobile: "",
    },
    type: "wallet_coins_darkBrown",
    price: 249,
    details:
      "ארנק עור לגבר בצבע חום כהה עם חריטה בעיצוב אישי.הארנק עשוי מעור איטלקי איכותי בעל תכולת ארנק מקסימאלית >>",
    category: "wallet",
    shortName: "",
    tomixProduct: false,
    staging: false,
    image:
      "https://assets.nameitonsteel.com/products/wallet_coins_darkBrown/coins_brown_main_new.webp",
    thumbImage:
      "https://assets.nameitonsteel.com/products/wallet_coins_darkBrown/coins_brown_main_new.webp",
    name: "ארנק לגבר עם חריטה מעור חום - אחסון פנימי ענק",
    renderOrder: "0",
    content:
      "<h2>&nbsp;ארנק עם חריטה – מתנה אישית לגבר</h2><p>ארנק בעיצוב אישי הפך למוצר ייחודי ואישי ביותר מכיוון שהוא מצד אחד שימושי (למי מאיתנו אין ארנק?) ומצד שני מוצר עם הקדשה אישית ומרגשת שהולך איתנו לכל מקום. באתר שלנו תמצאו מגוו ארנקי עור עם חריטה, ארנק דמוי עוד עם חריטה, ארנק שולף כרטיסים עם חריטה, חריטה על ארנק, ארנק לגבר עם חריטה, וארנק לאישה עם חריטה, ושלל ארנקים עם הקדשה לבחירתכם.</p><p><br></p><h2>&nbsp;כיצד מעצבים ארנק עם חריטה באתר?</h2><p>ארנק בעיצוב אישי נעשה בקלות דרך מערכת העיצוב שלנו, פשוט בוחרים ארנק, מוסיפים הקדשה וסמל. אנחנו כבר נקבל את העיצוב שלכם ונחרוט בדיוק לפי איך שעיצבתם.</p><p><br></p><h2>&nbsp;כיצד נעשית החריטה על הארנק</h2><p>החריטה על ארנק העשוי מעור אמיתי או טבעוני נעשית באמצעות טכנולוגיית CO2 Laser.</p><p>קרני הלייזר צורבות את משטח העור ומורידות שכבה עדינה אשר משאירה צורה חרוטה לפי העיצוב האישי שלכם על הארנק.</p><p>החריטה אינה פוגמת באיכות הארנק אלא רק מוסיפה יופי ומיוחדות.</p>",
    fullDesc:
      "<h2>ארנק עם חריטה - אחסון פנימי ענק</h2><p>ארנק עור איטלקי לגבר בצבע חום כהה בגוון טבעי עם חריטה בעיצוב אישי.</p><p>הארנק עשוי מעור איטלקי איכותי ובעל תכולה מירבית.</p><p>ארנק חזק, עמיד במיוחד ונוח לנשיאה, מידותיו הן 9*12 ס״מ.</p><p>ארנק עור עם חריטה הוא אחת המתנות היפות והשימושיות ביותר שאפשר להעניק לגבר.</p><p><br></p><h2>תכולת אחסון ענקית הכוללת:</h2><ul><li>4 תאי כרטיסי אשראי לשליפה מהירה</li><li>תא אחסון גדול למטבעות</li><li>2 תאים מאורכים לשטרות</li><li>בטן נשלפת עם מקום לתמונות וכרטיסי ביקור</li><li>מקום לעוד 6-8 כרטיסי אשראי בבטן הארנק</li><li>אפשרות להפיכתו לדק - על ידי הוצאת בטן האנרק</li></ul>",
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Wallets%2FNIOS_logoed%2Fcoins_wallet_darkBrown_pic1.jpg?alt=media&token=49a47112-ed10-4087-ba77-d1171f478525",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Wallets%2FNIOS_logoed%2Fcoins_wallet_darkBrown_pic0.jpg?alt=media&token=3519bafa-2d2e-4435-a70c-81dce0273f91",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Wallets%2FNIOS_logoed%2Fcoins_wallet_darkBrown_pic2.jpg?alt=media&token=fa8cee12-bb11-453a-ba6d-50bd49f0d39d",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2Frand%2Fleather_pic_portrait.png?alt=media&token=031dd054-413b-402d-aa30-19378763e5d3",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch24%2F9.png?alt=media&token=740dfff7-a3cb-469b-b307-7ba865878340",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch20%2FWhatsApp%20Image%202021-10-11%20at%2016.11.50%20(1).jpeg?alt=media&token=90d1a491-819d-4bd4-a5bc-857eeb7b82cf",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch24%2FWhatsApp%20Image%202021-11-03%20at%2015.53.46.jpeg?alt=media&token=fdd21843-8c52-4081-a701-3a1e841485d8",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch20%2FWhatsApp%20Image%202021-10-11%20at%2016.11.50.jpeg?alt=media&token=23c7c58e-41ca-452b-b951-ce58109b7392",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch20%2FWhatsApp%20Image%202021-10-07%20at%2012.00.58%20(1).jpeg?alt=media&token=1ad07539-285d-4394-86b1-320d9f233a21",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch19%2FWhatsApp%20Image%202021-10-04%20at%2016.56.50.jpeg?alt=media&token=8ea111a1-6284-4a0f-a593-daa06c0c46b1",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch21%2FWhatsApp%20Image%202021-10-18%20at%2016.46.21.jpeg?alt=media&token=1f11aad8-c6fd-42f8-b4ac-dbf6905f48ba",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch19%2FWhatsApp%20Image%202021-10-04%20at%2016.56.51.jpeg?alt=media&token=8ef2970a-393c-4085-ba31-a24a8275f815",
    ],
    tags: [
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "ארנקים-לגבר",
      "ארנקים-עם-הקדשה",
      "מתנה-למפקד",
      "market.html",
      "משפטים-לחריטה-על-ארנק",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
      "ארנקים-עם-תמונה",
    ],
    bestSeller: true,
    stock: 11,
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_chef21_main.jpeg?alt=media&token=6404b2df-2971-4ba2-9317-a1265a9d447f",
    types: [],
    multiDesign: false,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_chef21_widget_dt.jpeg?alt=media&token=3dc42a07-8c72-40e5-8768-fc731ee4d51c",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_chef21_widget_mw.jpeg?alt=media&token=8cf82390-efd0-48ec-ab57-b07cf039562f",
    },
    type: "arcos21_chef",
    content: "",
    bestSeller: false,
    name: 'סכין שף עם חריטה בעלת להב באורך 21 ס"מ ארקוס Arcos',
    details:
      'סכין שף עם חריטה בעלת להב באורך 21 ס"מ ארקוס Arcos לשימוש רב תחליטי במטבח',
    category: "chef",
    shortName: "ארקוס שף",
    tomixProduct: false,
    shouldDesign: true,
    staging: false,
    price: 249,
    thumbImage:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_chef21_main.jpeg?alt=media&token=6404b2df-2971-4ba2-9317-a1265a9d447f",
    renderOrder: "1",
    stock: 11,
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch14%2FWhatsApp%20Image%202021-08-29%20at%2016.13.21.jpeg?alt=media&token=3b9a3edd-1744-4cbe-a1a7-f3e8fe45af2e",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch15%2FWhatsApp%20Image%202021-09-12%20at%2021.00.46%20(2).jpeg?alt=media&token=cdb53e8d-fd58-4a33-9422-2326e95822ae",
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/Batches(Massive_gallery)%2Fbatch30%2F5.jpg?alt=media&token=ab1d5649-77cd-473d-8dc2-42b8ed8d6e50",
    ],
    tags: [
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "מתנה-למפקד",
      "מתנה-לחג",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
      "משפטים-לחריטה-על-סכין",
    ],
    fullDesc:
      '<p>סכין שף עם חריטת לייזר של חברת ארקוס Arcos הספרדית.</p><p>הסכין בעלת להב באורך 21 ס"מ וידית ארגונומית בציפוי סיליקון לשיפור האחיזה.</p><p>סכין השף בעלת להב חלק ומתאימה לשימוש מקצועי והתעסקות מעמיקה עם בשרים, עופות, ירקות ופירות.</p><p>סכין איכותית עם ביצועים מעולים אשר נשמרת למשך זמן ארוך.</p><p>החריטה על הסכין בצבע שחור ואינה ניתנת להסרה.</p>',
  },
  {
    shouldDesign: true,
    image:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_nordica_santoku_main.jpg?alt=media&token=0dbc1b18-1b50-4ce0-9c47-fa0352b2d02e",
    types: [],
    multiDesign: false,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_nordica_santoku_widget_DT.jpg?alt=media&token=53cc1c09-2c7f-402c-8bdb-580468e56726",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_nordica_santoku_widget_MW.jpg?alt=media&token=0d889c4b-3edc-43b0-acf3-baa3769ee3f7",
    },
    type: "arcos_chef_nordica_santoku",
    content: "",
    productImages: [],
    thumbImage:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_nordica_santoku_main.jpg?alt=media&token=0dbc1b18-1b50-4ce0-9c47-fa0352b2d02e",
    price: 319,
    bestSeller: false,
    name: 'סכין סנטוקו מחוזקת עם חריטה בעלת להב באורך 20 ס"מ ארקוס Arcos',
    details:
      'סכין סנטוקו מחוזקת עם חריטה בעלת להב באורך 20 ס"מ ארקוס Arcos סדרת נורדיקה',
    category: "chef",
    shortName: "ארקוס נורדיקה סנטוקו",
    stock: 10,
    tomixProduct: false,
    staging: false,
    renderOrder: "1",
    tags: [
      "מתנות-ליום-הולדת-לגבר",
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "סכין-שף-יפנית",
      "משפטים-לחריטה-על-סכין",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
    fullDesc:
      '<p>סכין סנטוקו עם חריטת לייזר של חברת ארקוס Arcos הספרדית עם ידית עץ ולהב מחוזק.</p><p>הסכין בעלת להב באורך 20 ס"מ וידית ארגונומית מעץ, בעלת עיצוב יפני מודרני.</p><p>הסכין בעלת להב חלק ומתאימה לשימוש מקצועי והתעסקות מעמיקה עם בשרים, עופות, ירקות ופירות.</p><p>סכין איכותית עם ביצועים מעולים אשר נשמרת למשך זמן ארוך.</p><p>החריטה על הסכין בצבע שחור ואינה ניתנת להסרה.</p>',
  },
  {
    types: [],
    multiDesign: false,
    type: "bamboo_big",
    content: "",
    name: 'קרש חיתוך עם חריטה מעץ במבוק באורך 40 ס"מ',
    details:
      "קרש חיתוך עם הקדשה בחריטה אישית מעץ במבוק. מידת הקרש חיתוך עם חריטה 40/30/1.5",
    category: "butcher",
    shortName: "קרש חיתוך במבוק גדול",
    tomixProduct: false,
    shouldDesign: true,
    staging: false,
    stock: 9,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery%2Fbamboo_big_widget.jpeg?alt=media&token=55eb4fc3-e570-4370-b59d-f62f55cd074c",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery%2Fbamboo_big_widget.jpeg?alt=media&token=55eb4fc3-e570-4370-b59d-f62f55cd074c",
    },
    image: "https://assets.nameitonsteel.com/products/bamboo_big/1.webp",
    thumbImage: "https://assets.nameitonsteel.com/products/bamboo_big/1.webp",
    tags: [
      "מתנות-לגבר",
      "מתנה-לראש-השנה",
      "מתנות-ליום-הולדת-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "מתנה-למפקד",
      "birthday-gifts",
      "בוצר-מתנה",
      "משפטים-לחריטה-על-בוצר",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-24%20at%2016.28.35%20(1).jpeg?alt=media&token=65d7116c-ab85-49d9-a648-c3f4c12adff2",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-24%20at%2016.28.33%20(2).jpeg?alt=media&token=2a3e5a2b-ae3f-4bea-8beb-cb5ff57861bc",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-24%20at%2014.19.04%20(1).jpeg?alt=media&token=e49f1c28-4c14-45a5-b6b5-387cd5cff5e8",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch23%2FWhatsApp%20Image%202021-11-02%20at%2016.55.42%20(2).jpeg?alt=media&token=c8695588-9b5c-4379-b32b-702206187c60",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch23%2FWhatsApp%20Image%202021-11-02%20at%2016.55.19%20(1).jpeg?alt=media&token=f543cc8a-be07-4a19-b565-a506098ba7fb",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-24%20at%2016.28.32.jpeg?alt=media&token=e28d5911-33d0-44c0-964e-d5b5033237ce",
      "https://storage.nameitonsteel.com/productImages/bamboo_big/1.webp",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch20%2FWhatsApp%20Image%202021-10-11%20at%2016.11.51%20(1).jpeg?alt=media&token=40fc9c7a-6550-4e95-9dde-d92137e01044",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch25%2FWhatsApp%20Image%202021-11-14%20at%2011.09.00%20(2).jpeg?alt=media&token=3ea301af-5d3f-4865-9f5d-554f7ef46bd6",
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/Batches(Massive_gallery)%2FBatch28%2FWhatsApp%20Image%202021-12-06%20at%2013.03.42%20(1).jpeg?alt=media&token=78e74e66-0228-494c-8487-7c651c88ce68",
    ],
    fullDesc:
      "<h2>מידות ומאפיינים:</h2><ul><li>גודל: 40x30x1.5 ס\"מ</li><li>תעלה לניקוז נוזלים בקצוות הבוצ'ר</li></ul><p><br></p><h2>על הקרש חיתוך בוצ'ר עם חריטה:</h2><p>קרש חיתוך עם הקדשה בחריטה אישית מעץ במבוק - מגיע עם מסילה לניקוז הנוזלים בקצוות הבוצ'ר.</p><p>החריטה על קרש החיתוך מגיעה בגוון חום כהה-שחור ונעשית על ידי מכונת לייזר.</p><p>עיצוב קרש החיתוך נעשה בקלות ובמהירות באתר - ניתן לחרוט טקסטים בכל השפות ולהוסיף לוגואים ממבחר הלוגואים באתר.</p><p>המחיר כולל חריטת לייזר ומשלוח עד דלת הבית.</p>",
    bestSeller: false,
    renderOrder: "1",
    price: 229,
  },
  {
    shouldDesign: true,
    image:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fnum254r.jpg?alt=media&token=b1887c59-7175-4aa0-8d2d-e9df3051d9ef",
    renderOrder: "1",
    types: [],
    multiDesign: false,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fnum2r4.jpg?alt=media&token=95679aef-9af9-4610-9ce3-76c4671d8092",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fnum2r4.jpg?alt=media&token=95679aef-9af9-4610-9ce3-76c4671d8092",
    },
    type: "bracelet_3names",
    content: "",
    fullDesc:
      '<p>צמיד לגבר אשר משלב&nbsp;עור שחור עם 3 חרוזי כסף עם חריטה אישית.</p><p>ניתן לחרוט את שמות הילדים \\ השמות של שני בני הזוג או כל דבר נוסף שתרצו.</p><p>צמיד קלאסי אשר ישתלב בצורה מצוינת עם צמידים נוספים או שעון.</p><p>הצמיד עמיד למים ב100%</p><p><br></p><p><br></p><h2>מאפיינים:</h2><ul><li>עמיד בפני מים</li><li>אורך כולל של 21 ס"מ</li><li>3 טבעות לחריטה</li></ul>',
    productImages: [],
    thumbImage:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fnum254r.jpg?alt=media&token=b1887c59-7175-4aa0-8d2d-e9df3051d9ef",
    price: 199,
    bestSeller: false,
    name: "צמיד שמות עם חריטה לגבר - 3 חרוזי כסף",
    details: "צמיד שמות עם חריטה לגבר - 3 חרוזי כסף",
    category: "other",
    shortName: "צמיד לגבר עם חריטה",
    stock: 15,
    tomixProduct: false,
    staging: false,
    tags: [
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "מתנה-למפקד",
      "market.html",
      "birthday-gifts",
      "מתנה-לראש-השנה",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
      "jewelry",
      "תכשיטים-עם-הקדשה",
    ],
  },
  {
    shouldDesign: true,
    image:
      "https://assets.nameitonsteel.com/products/bracelet_4names/num2_1.webp",
    renderOrder: "1",
    types: [],
    multiDesign: false,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fnum3e3.jpg?alt=media&token=5ecfed3f-4ccd-479e-8813-a8cfa3218846",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fnum3e3.jpg?alt=media&token=5ecfed3f-4ccd-479e-8813-a8cfa3218846",
    },
    type: "bracelet_4names",
    content: "",
    fullDesc:
      '<p>צמיד לגבר אשר משלב&nbsp;עור שחור עם 4 חרוזי כסף עם חריטה אישית.</p><p>ניתן לחרוט את שמות הילדים \\ השמות של שני בני הזוג או כל דבר נוסף שתרצו.</p><p>צמיד קלאסי אשר ישתלב בצורה מצוינת עם צמידים נוספים או שעון.</p><p>הצמיד עמיד למים ב100%</p><p><br></p><p><br></p><h2>מאפיינים:</h2><ul><li>עמיד בפני מים</li><li>אורך כולל של 21 ס"מ</li><li>4 טבעות לחריטה</li></ul>',
    productImages: [],
    thumbImage:
      "https://assets.nameitonsteel.com/products/bracelet_4names/num2_1.webp",
    bestSeller: false,
    name: "צמיד שמות עם חריטה לגבר - 4 חרוזי כסף",
    details: "צמיד שמות עם חריטה לגבר - 4 חרוזי כסף",
    category: "other",
    shortName: "צמיד לגבר עם חריטה",
    stock: 15,
    tomixProduct: false,
    staging: false,
    price: 229,
    tags: [
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "מתנה-למפקד",
      "market.html",
      "birthday-gifts",
      "מתנה-לראש-השנה",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
      "jewelry",
      "תכשיטים-עם-הקדשה",
    ],
  },
  {
    shouldDesign: true,
    image:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2FUntitled%20design%20-%202022-10-08T202510.768.png?alt=media&token=d2a58afc-4f62-4f06-a7e1-c2b3c7f244e4",
    renderOrder: "1",
    types: [],
    multiDesign: false,
    type: "bracelet_crown",
    content: "",
    fullDesc:
      '<p>צמיד חריטה קלאסי לגבר אשר משלב פלטה כסופה ושרשרת גורמט קלאסית.</p><p>צמיד מדהים, גברי ומלא נוכחות.</p><p>ניתן לחרוט שמות, תאריכים או סמלים.</p><p>הצמיד עמיד למים ב100%</p><p><br></p><p><br></p><h2>מאפיינים:</h2><ul><li>עמיד בפני מים</li><li>אורך כולל של 21 ס"מ + שרשרת הארכה של 5 ס"מ</li><li>צבע כסף</li><li>חומר - סטיינלס סטיל Stainless Steel</li></ul>',
    thumbImage:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2FUntitled%20design%20-%202022-10-08T202510.768.png?alt=media&token=d2a58afc-4f62-4f06-a7e1-c2b3c7f244e4",
    price: 129,
    bestSeller: false,
    name: "צמיד עם חריטה לגבר - לולאות כסף",
    details: "צמיד עם חריטה לגבר - לולאות כסף",
    category: "other",
    shortName: "צמיד לגבר עם חריטה",
    tomixProduct: false,
    staging: false,
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fjpggggg555.jpg?alt=media&token=c10b94fa-70c7-4252-8a93-63051a6df2f0",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fhorn%20image.jpg?alt=media&token=70941401-67d1-4c21-915a-ed9608ae31e8",
    ],
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fhorndesgn22.png?alt=media&token=244d4c9f-16c9-4c5d-8b32-b01eae0516b3",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Bracelets%2Fhorndesgn22.png?alt=media&token=244d4c9f-16c9-4c5d-8b32-b01eae0516b3",
    },
    tags: [
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "מתנה-למפקד",
      "market.html",
      "birthday-gifts",
      "מתנה-לראש-השנה",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
      "jewelry",
      "תכשיטים-עם-הקדשה",
    ],
    stock: 11,
  },

  {
    shouldDesign: true,
    "shortName ": "Naaman Butcher (small)",
    type: "naaman_butcher_small_engrave",
    price: 199,
    category: "butcher",
    staging: false,
    renderOrder: 2,
    stock: 11,
    designImage: {
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/widgetPhotos_compressed%2Fnaaman_small.jpg?alt=media&token=ed6732d9-035c-4ea4-8123-813da51b666a",
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/widgetPhotos_compressed%2Fnaaman_small.jpg?alt=media&token=ed6732d9-035c-4ea4-8123-813da51b666a",
    },
    name: "בוצ'ר עץ שיטה עם חריטה באורך 35 ס\"מ\n",
    details:
      "בוצ'ר עץ שיטה עם הקדשה אישית. קרש חיתוך עם חריטה במידה 35/25/1.5 מגיע עם הקדשה בעיצוב אישי.\n",
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch3%2Fc123cec21.jpeg?alt=media&token=653e0591-cee3-4693-bcb2-9cfaecf07984",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch11%2FWhatsApp%20Image%202021-07-28%20at%2017.33.16.jpg?alt=media&token=09c5ad9d-7520-4c08-bdb7-c36543cf780c",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch3%2Fce32132.jpeg?alt=media&token=26b4b01b-1b67-4c05-acfb-4acae809e55a",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch4%2Fc234c3.jpeg?alt=media&token=894b7f29-0e0c-4017-b817-56737a2c368a",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch4%2Fc13c213.jpeg?alt=media&token=55bb0c6c-7f28-40f6-a4f7-0290438d3998",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery%2Fnaaman_small_engrave_pic1.jpeg?alt=media&token=31209ef1-cbd0-44ec-b190-4b66a7884e98",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery%2Fnaaman_small_engrave_pic2.jpeg?alt=media&token=87cad206-766f-4a1b-9308-89ec7bbc0e2e",
    ],
    types: [],
    multiDesign: false,
    bestSeller: false,
    tomixProduct: false,
    content: "",
    shortName: 'קרש חיתוך נעמן באורך 35 ס"מ',
    image:
      "https://assets.nameitonsteel.com/products/naaman_butcher_small_engrave/4.webp",
    thumbImage:
      "https://assets.nameitonsteel.com/products/naaman_butcher_small_engrave/4.webp",
    tags: [
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "birthday-gifts",
      "מתנה-למפקד",
      "בוצר-מתנה",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
      "משפטים-לחריטה-על-בוצר",
    ],
    fullDesc:
      "<h2>מידות ומאפיינים:</h2><ul><li>גודל: 35x25x1.5 ס\"מ</li><li>גוון: חום כהה-בהיר</li></ul><p><br></p><h2>על הקרש חיתוך בוצ'ר עם חריטה:</h2><p>קרש חיתוך עם הקדשה בחריטה אישית מעץ שיטה.</p><p>החריטה על קרש החיתוך מגיעה בגוון חום כהה-שחור ונעשית על ידי מכונת לייזר.</p><p>עיצוב קרש החיתוך נעשה בקלות ובמהירות באתר - ניתן לחרוט טקסטים בכל השפות ולהוסיף לוגואים ממבחר הלוגואים באתר.</p><p>המחיר כולל חריטת לייזר ומשלוח עד דלת הבית.</p>",
  },
  {
    shouldDesign: true,
    type: "olive_butcher_engrave",
    category: "butcher",
    shortName: "פלטת עץ זית",
    designWarningMessage: "מיקום החריטה ניתן לשינוי והתאמה בהתאם לצורת הפלטה",
    staging: false,
    bestSeller: true,
    types: [],
    multiDesign: false,
    tomixProduct: false,
    content: "",
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGallery3%2Folive_new_widget.jpg?alt=media&token=edcaf13f-2931-438c-8786-ff3f3e4a983a",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGallery3%2Folive_new_widget.jpg?alt=media&token=edcaf13f-2931-438c-8786-ff3f3e4a983a",
    },
    image:
      "https://assets.nameitonsteel.com/products/olive_butcher_engrave/10.webp",
    thumbImage:
      "https://assets.nameitonsteel.com/products/olive_butcher_engrave/10.webp",
    tags: [
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "birthday-gifts",
      "מתנה-למפקד",
      "בוצר-מתנה",
      "משפטים-לחריטה-על-בוצר",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch14%2FWhatsApp%20Image%202021-08-29%20at%2016.17.48.jpeg?alt=media&token=48fe108c-c2f7-4c42-b531-6c3d04247fbf",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch15%2FWhatsApp%20Image%202021-09-13%20at%2016.17.10.jpeg?alt=media&token=5357c6c2-ba1b-42c0-b557-5c28bdb7c301",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch15%2FWhatsApp%20Image%202021-09-13%20at%2016.17.09.jpeg?alt=media&token=5b92a3b0-f59d-419a-9da4-b76b83bc5611",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch16%2FWhatsApp%20Image%202021-09-14%20at%2016.06.56.jpeg?alt=media&token=f94c5e8c-8415-456d-9e19-48fa4cf2cf87",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch16%2FWhatsApp%20Image%202021-09-14%20at%2016.06.55.jpeg?alt=media&token=b24e5755-62da-4b36-b4e8-5463a1906463",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery2%2Folive4.jpeg?alt=media&token=228c175d-8a2c-41fb-b11e-1f7c29f33359",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery2%2Folive2.jpeg?alt=media&token=4c7ed6ea-fa2c-42a5-9f64-c6d3c84c80d8",
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/Batches(Massive_gallery)%2Fbatch18%2FWhatsApp%20Image%202021-09-30%20at%2018.41.14.jpeg?alt=media&token=42cafc58-1023-4f8c-a26b-51a52266463e",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch19%2FWhatsApp%20Image%202021-10-04%20at%2016.56.43.jpeg?alt=media&token=eb384a72-a34c-4ba0-a99e-062c9028837e",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch19%2FWhatsApp%20Image%202021-10-04%20at%2016.56.54%20(2).jpeg?alt=media&token=b028f735-acc1-41c1-a0bc-daa046dc0573",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch20%2FWhatsApp%20Image%202021-10-07%20at%2012.00.55%20(1).jpeg?alt=media&token=77f2e091-fd3a-403d-8bda-7637b3930ee8",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch20%2FWhatsApp%20Image%202021-10-07%20at%2012.00.56%20(1).jpeg?alt=media&token=cfa81f10-1d87-458c-8ef3-a93eb8dadf92",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-24%20at%2016.28.31.jpeg?alt=media&token=186e3d47-1e9c-4fff-8364-b7679e17a3c0",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch23%2FWhatsApp%20Image%202021-11-02%20at%2016.55.13.jpeg?alt=media&token=5801f891-6121-4a95-b8bd-e5568bfebbb8",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch23%2FWhatsApp%20Image%202021-11-02%20at%2016.55.17%20(2).jpeg?alt=media&token=36d9f89f-8f48-4824-bf42-1ec781529102",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch25%2FWhatsApp%20Image%202021-11-14%20at%2011.07.32%20(4).jpeg?alt=media&token=5d255b6a-e0a8-4813-b749-97b12efe2f59",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch25%2FWhatsApp%20Image%202021-11-14%20at%2011.07.33%20(5).jpeg?alt=media&token=76d17110-79a3-4e53-982f-b3107addd180",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch26%2FWhatsApp%20Image%202021-11-22%20at%2016.13.07.jpeg?alt=media&token=896aad13-4270-4d43-b029-10c4a9e6912a",
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/Batches(Massive_gallery)%2Fbatch31%2F2.png?alt=media&token=1f144750-6a2f-4411-9092-eefa19dd689e",
    ],
    name: 'קרש חיתוך עם חריטה מעץ זית טבעי באורך 40 ס"מ',
    details:
      'קרש חיתוך עם חריטה העשוי מעץ זית מלא בצורה טבעית. הפלטה מגיעה במידה 40x20x2.5 ס"מ. מחיר הקרש חיתוך כולל חריטת לייזר ומשלוח עד דלת הבית. ',
    fullDesc:
      "<h2>מידות ומאפיינים:</h2><ul><li>גודל: 40x20x2.5 ס\"מ</li><li>תעלה לניקוז נוזלים בקצוות הבוצ'ר</li><li>צורה טבעית ומשתנה</li></ul><p><br></p><h2>על הקרש חיתוך בוצ'ר עם חריטה:</h2><p>פלטת עץ מלא עם חריטה בצורה טבעית העשויה מעץ זיתי קלמטה, צורת הפלטה וגודלה משתנים מכיוון שאלה פרוסות עץ טבעי.</p><p>הבוצ׳ר מגיע עם תעלה לניקוז נוזלים אשר תורמת לסביבת עבודה נקייה וסטרילית.</p><p>עץ זית מאופיין כעץ קשיח ועמיד מאוד לאורך שנים רבות.</p><p>קרש החיתוך עם החריטה עשוי מעץ זית יווני מלא ברמה הגבוהה ביותר.</p><p>עיצוב קרש החיתוך נעשה בקלות ובמהירות באתר - ניתן לחרוט טקסטים בכל השפות ולהוסיף לוגואים ממבחר הלוגואים באתר.</p><p>המחיר כולל חריטת לייזר ומשלוח עד דלת הבית.</p><p>הערה: טווח רוחב הקרש נע בין 20-30 ס\"מ ומשתנה בין כל מוצר.</p>",
    renderOrder: "2",
    price: 399,
    stock: 11,
  },

  {
    shouldDesign: true,
    image:
      "https://assets.nameitonsteel.com/products/steak_knife_6_wood/steakKnives4.webp",
    renderOrder: "2",
    types: [],
    multiDesign: false,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/widgetPhotos_compressed%2FsteakKnife.jpg?alt=media&token=cd0591ac-143d-49ec-9045-7c9a3dcd86ea",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGallery6%2FsteakKnife_widget_MW.JPG?alt=media&token=590253b5-9190-415d-8e67-fe959cefcb4d",
    },
    type: "steak_knife_6_wood",
    content: "",
    fullDesc:
      '<p>סט 6 סכיני סטייק עם חריטה אישית (סט זה מכיל 6 סכיני סטייק עם חריטה ולא 4).</p><p>אורך להב הסכין הוא 12 ס"מ.</p><p>החריטה בכל 6 הסכינים היא זהה וצבעה הוא שחור.</p><p><br></p>',
    tags: [
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "birthday-gifts",
      "מתנה-למפקד",
      "בוצר-מתנה",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch8%2FWhatsApp%20Image%202021-07-05%20at%2009.40.41.jpeg?alt=media&token=9dcedc66-d100-45dc-a00a-ef0820031c4d",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch12%2FWhatsApp%20Image%202021-08-12%20at%2014.56.06%20(1).jpeg?alt=media&token=b28cde1a-dae1-49da-baa5-d1eaf4f57760",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch10%2FWhatsApp%20Image%202021-07-22%20at%2010.52.00.jpeg?alt=media&token=dcbf75e2-d4bb-4fe5-bae0-78e4d30a5ac4",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch9%2FWhatsApp%20Image%202021-07-19%20at%2015.23.34.jpg?alt=media&token=43a401ee-343a-4c69-a44a-f54026b9925f",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch11%2FWhatsApp%20Image%202021-07-28%20at%2017.33.17%20(1).jpeg?alt=media&token=aa4b18c8-6c74-46ac-b1c0-5eabb1154f3f",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery%2FsteakKnife.jpg?alt=media&token=6cc8e6da-271e-4a26-8005-f7ae180a6889",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch26%2FWhatsApp%20Image%202021-11-22%20at%2016.13.07%20(9).jpeg?alt=media&token=bb0e544e-2b99-424a-a7a0-280328ea6521",
    ],
    thumbImage:
      "https://assets.nameitonsteel.com/products/steak_knife_6_wood/steakKnives4.webp",
    price: 299,
    bestSeller: false,
    name: "סט 6 סכיני סטייק עם חריטה אישית",
    details:
      "סט 6 סכיני סטייק עם חריטה אישית, סכיני הסטייק ברמה הגבוהה ביותר מיוצרים בברזיל ומתאימים לארוחות בשרים ולחיתך בשר.",
    category: "meatKnife",
    shortName: "Steak knife",
    stock: 11,
    tomixProduct: false,
    staging: false,
  },
  {
    shouldDesign: true,
    types: ["dick26", "olive_butcher_engrave"],
    multiDesign: true,
    designImage: {
      desktop: "",
      mobile: "",
    },
    type: "zait_dick26",
    name: "קרש חיתוך עץ זית וסכין בשר F.DICK עם חריטה",
    details:
      "מארז הכולל: סכין מעוגלת עם חריטה אישית + בוצ'ר עץ זית מלא  + מגבת קיטן + ארוז כמתנה.",
    category: "package",
    shortName: "",
    stock: 11,
    tomixProduct: false,
    staging: false,
    renderOrder: "2",
    content:
      "<h2>&nbsp;תהליך יצירת סכין שף וקרש חיתוך עם חריטה</h2><p>החריטה על הסכין נעשית ע\"י מכונת חריטה אשר צורבת צריבה שחורה על הסכין ומשאירה את ההקדשה על הסכין בצורה בולטת לעין. חריטה על בוצ'ר נעשית ע\"י מכונת חריטה על עץ אשר צורבת את משטח העץ (קרש חיתוך או בוצ'ר), ומשאירה חלקים צרובים שלא ניתנים להסרה. בוצ'ר עם חריטה מגיע במבחר גווני חריטה כתלות בדחיסות וגוון חומר הגלם. כל המוצרים עומדים בתקנים המחמירים ואישורי NSF. להב הסכינים עשוי ממתכת גרמנית בתרכובת 1.4116 העשויה מפחמן, כרום, ונדיום, מוליבדן ועוד.</p><p><br></p><h2>&nbsp;למי מתאים מארז של סכין וקרש חיתוך עם חריטה</h2><p>מארז של סכין וקרש חיתוך עם חריטה יכול להתאים לכל קשת האנשים ולמגוון גדול של אירועים. קרש חיתוך עם חריטה יתאים לשימוש יומיומי של הגשת מזון לארוחת הערב או פיקניק ועד לשימוש להגשה וחיתוך נתחי בשר ואילו הסכין עם חריטה תתאים לשימוש יומיומי החל מחיתוך סלט ועד לשימוש קולינרי ברמה המקצועית ביותר. חריטה על סכין שף או בוצ'ר עם חריטה מסמל יותר מהקדשה אישית, זו הקדשה אישית על מוצר שימושי שמשתמשים בו על בסיס קבוע ולאורך שנים ארוכות.</p><p><br></p><h2>&nbsp;איך תהליך הזמנת סכין ובוצ'ר עם חריטה מתבצע</h2><p>כל מה שעליכם לעשות זה לחשוב על הקדשה על הסכין, הקדשה על הבוצ'ר, לעצב בקלות באתר שלנו ולהזמין. מיד לאחר ההזמנה, הצוות שלנו יבחן את העיצוב שהכנתם ויפנה אליכם במידה ומשהו לא ברור על מנת שהחריטה על הסכין והחריטה על הקרש חיתוך יהיו מושלמים. מארז של סכין וקרש חיתוך עם חריטה יכול להתאים כמתנה המושלמת לאדם שחוגג יום הולדת, מעבר דירה, או כל אירוע אחר (כמובן שאתם תמיד מוזמנים לפנק את עצמכם עם מתנה אישית של סכין שף עם חריטה).</p><p><br></p><h2>&nbsp;סכין וקרש חיתוך עם חריטה – מתנה ממותגת ואישית שתמיד כיף להעניק</h2><p>בוצ'ר וסכין עם חריטה יוצרים יחד את המארז חריטה עם הקדשה אישית האיכותי והשימושי ביותר. צוות החרטים המיומן שלנו שם דגש בראש ובראשונה לדיוק המוצר, לפי העיצוב שבחרתם תוך כדי דגש על אסתטיקה וסימטריה בכל פריט. חריטה על סכין נעשית על ידי מכונה ייחודית לחריטה על סכינים, וחריטה על קרש חיתוך (חריטה על בוצ'ר) נעשית על ידי מכונה המתאימה לחריטה על עץ.</p><p><br></p><h2>&nbsp;לא מסתדרים עם עיצוב אישי באתר?</h2><p>תמיד ניתן להשתמש באופציה ל-\"עיצוב מהיר\" ואנחנו כבר נדאג לעצב לכם את מתנת החריטה בצורה המקצועית ביותר. אנחנו בניוס חריטה אישית כאן על מנת לבצע את העבודה בצורה הטובה ביותר. במידה ותרצו ייעוץ או הכוונה לבחירת מוצר אתם תמיד מוזמנים לפנות אלינו ב-WhatsApp או להתקשר למספר 051-2280192 ונשמח לייעץ ולהכווין אתכם.</p>",
    bestSeller: true,
    image: "https://assets.nameitonsteel.com/products/zait_dick26/23.webp",
    thumbImage: "https://assets.nameitonsteel.com/products/zait_dick26/23.webp",
    tags: [
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "מתנה-למפקד",
      "birthday-gifts",
      "בוצר-מתנה",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch16%2FWhatsApp%20Image%202021-09-14%20at%2016.06.54%20(1).jpeg?alt=media&token=8fb56e84-d07f-4647-a15c-f6d2220deb33",
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/Batches(Massive_gallery)%2Fbatch18%2FWhatsApp%20Image%202021-09-30%20at%2018.41.13%20(2).jpeg?alt=media&token=92f0506b-9660-4702-85d4-0d8d6812263e",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery2%2FdickZait.jpeg?alt=media&token=d5f075da-18bd-44ab-adf3-333c381e719b",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch14%2FWhatsApp%20Image%202021-08-29%20at%2016.17.48.jpeg?alt=media&token=48fe108c-c2f7-4c42-b531-6c3d04247fbf",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch16%2FWhatsApp%20Image%202021-09-14%20at%2016.06.56.jpeg?alt=media&token=f94c5e8c-8415-456d-9e19-48fa4cf2cf87https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch16%2FWhatsApp%20Image%202021-09-14%20at%2016.06.56.jpeg?alt=media&token=f94c5e8c-8415-456d-9e19-48fa4cf2cf87",
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/Batches(Massive_gallery)%2Fbatch35%2F6.png?alt=media&token=941defaf-30f0-4024-8f2d-2c1ad05b6301",
    ],
    fullDesc:
      '<h2>תכולת המארז:</h2><ul><li>קרש חיתוך מעץ זית בצורה טבעית עם חריטה</li><li>סכין בשר להב גבוהה עם חריטה דיק F.DICK</li></ul><p><br></p><h2>גדלים ומידות:</h2><ul><li>מידות הקרש חיתוך: 40x20x2.5 ס"מ</li><li>סכין בשר: להב באורך 26 ס"מ</li></ul><p><br></p><h2>פרטים על המארז</h2><p>פלטת עץ מלא עם חריטה בצורה טבעית העשויה מעץ זיתי קלמטה, צורת הפלטה וגודלה משתנים מכיוון שאלה פרוסות עץ טבעי.</p><p>הבוצ׳ר מגיע עם תעלה לניקוז נוזלים אשר תורמת לסביבת עבודה נקייה וסטרילית.</p><p>סכין הבשר בעלת להב גבוה אשר מאפשר עבודה נוחה בשימוש עם עוף ובשר ובעלת ידית ארגונומית לשיפור האחיזה.</p><p>הסכין מעולה ומתאימה לחובבי בשר מתחילים ועד לקצבים המקצועיים ביותר.</p><p>החריטה על הבוצ\'ר בגוון חום-שחור כתלות בחלק העץ והחריטה על הסכין בצבע שחור ואינה ניתנת להסרה.</p>',
    price: 589,
  },
  {
    shouldDesign: true,
    image:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGallery6%2FMESA%2Falon_handle_main.jpg?alt=media&token=eeac1ec0-7a75-4b51-968b-df944807a77b",
    types: [],
    multiDesign: false,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGallery6%2FMESA%2Falon_handle_widget.jpg?alt=media&token=80c1d0a9-0602-43a8-8dcd-4baf4754e1ba",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGallery6%2FMESA%2Falon_handle_widget.jpg?alt=media&token=80c1d0a9-0602-43a8-8dcd-4baf4754e1ba",
    },
    type: "alon_handle",
    content: "",
    thumbImage:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGallery6%2FMESA%2Falon_handle_main.jpg?alt=media&token=eeac1ec0-7a75-4b51-968b-df944807a77b",
    price: 359,
    bestSeller: false,
    details:
      'קרש חיתוך עם חריטה עץ אלון מלא וידית אחיזה, קרש חיתוך במידה 50/33/3 ס"מ העשוי מעץ אלון כולל חריטה ותעלה לניקוז בשר.',
    category: "butcher",
    shortName: "בוצ'ר עץ אלון",
    tomixProduct: false,
    staging: false,
    name: "קרש חיתוך עם חריטה מעץ אלון מלא",
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch17%2FWhatsApp%20Image%202021-09-29%20at%2014.08.03%20(2).jpeg?alt=media&token=1614f0f0-36c2-4a28-8298-48d5e42e2569",
    ],
    stock: 1,
    renderOrder: "3",
    tags: [
      "market.html",
      "מתנה-לגבר",
      "מתנה-למפקד",
      "אביזרים-למטבח",
      "מתנות-לגבר",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
      "משפטים-לחריטה-על-בוצר",
    ],
    fullDesc:
      "<p>עץ אלון מלא עם חריטה וידית אחיזה. </p><p>הבוצ'ר במידה 50/33/3 ס\"מ עשוי אלון מלא כולל חריטה ותעלה לניקוז בשר. </p><p>חריטה על קרש חיתוך בוצ'ר עץ אלון מגיעה ברמה האיכותית ביותר בגלל דחיסות עץ האלון, אשר מקנה לחריטה צורה חדה ביותר ותבליט בבירור את העיצוב האישי על הבוצ'ר. </p><p>קרש חיתוך עם חריטה זה מגיע עם תעלה בשני צידי המוצר.</p>",
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_nordica_main.jpeg?alt=media&token=26c81471-3a90-4c75-84fa-67309eb365a5",
    renderOrder: "3",
    types: [],
    multiDesign: false,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_nordica_widget_dt.jpeg?alt=media&token=b10d32eb-902c-4483-a5fd-f2130b148c68",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_nordica_widget_mw.jpeg?alt=media&token=18419b2f-b4b4-4321-a2ed-56c50b10ee87",
    },
    type: "arcos_chef_nordica",
    content: "",
    bestSeller: false,
    name: 'סכין שף מחוזקת עם חריטה בעלת להב באורך 21 ס"מ ארקוס Arcos',
    details:
      'סכין שף מחוזקת עם חריטה בעלת להב באורך 21 ס"מ ארקוס Arcos סדרת נורדיקה',
    category: "chef",
    shortName: "ארקוס נורדיקה",
    tomixProduct: false,
    shouldDesign: true,
    staging: false,
    stock: 10,
    thumbImage:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Farcos_nordica_main.jpeg?alt=media&token=26c81471-3a90-4c75-84fa-67309eb365a5",
    price: 329,
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch15%2FWhatsApp%20Image%202021-09-12%20at%2021.00.46%20(3).jpeg?alt=media&token=78fab44b-1254-4807-a329-ebe7c962d326",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-25%20at%2016.21.18%20(1).jpeg?alt=media&token=284b8459-91d3-45ca-930f-325f2bce5016",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-25%20at%2016.21.18.jpeg?alt=media&token=743c7729-146e-4f65-9a8f-a47ffa1caf7c",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-24%20at%2016.28.34%20(2).jpeg?alt=media&token=04f770c6-7ffd-4d09-9b7b-7ea2fef6d4ff",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-24%20at%2016.28.35.jpeg?alt=media&token=2f01b19a-87d7-43a0-8036-149d34733f28",
    ],
    fullDesc:
      '<p>סכין שף עם חריטת לייזר של חברת ארקוס Arcos הספרדית עם ידית עץ ולהב מחוזק. </p><p>הסכין בעלת להב באורך 21 ס"מ וידית ארגונומית מעץ. </p><p>הסכין שף בעלת להב חלק ומתאימה לשימוש מקצועי והתעסקות מעמיקה עם בשרים, עופות, ירקות ופירות. </p><p>סכין איכותית עם ביצועים מעולים אשר נשמרת למשך זמן ארוך. </p><p>החריטה על הסכין בצבע שחור ואינה ניתנת להסרה.</p>',
    tags: [
      "מתנות-ליום-הולדת-לגבר",
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "סכין-שף-יפנית",
      "birthday-gifts",
      "מתנה-למפקד",
      "בוצר-מתנה",
      "משפטים-לחריטה-על-סכין",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
  },
  {
    shouldDesign: true,
    renderOrder: "3",
    types: ["shpahtel", "bamboo_big"],
    multiDesign: true,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGallery6%2Fpizza30_galgelet_widget.jpg?alt=media&token=87c17616-6144-4066-a62b-67d5910eef23",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGallery6%2Fpizza30_galgelet_widget.jpg?alt=media&token=87c17616-6144-4066-a62b-67d5910eef23",
    },
    type: "bakery_kit",
    content: "",
    price: 329,
    name: "מארז לאופים עם חריטה הכולל קרש חיתוך, שפכטל לבצק ומארוך",
    details:
      "מארז לאופים עם חריטה הכולל קרש חיתוך גדול עם חריטה, שפכטל לבצק עם חריטה ומארוך",
    category: "package",
    shortName: "Pizza Cutting Board",
    stock: 11,
    tomixProduct: false,
    staging: false,
    image: "https://assets.nameitonsteel.com/products/bakery_kit/26.webp",
    thumbImage: "https://assets.nameitonsteel.com/products/bakery_kit/26.webp",
    tags: [
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "birthday-gifts",
      "מתנה-למפקד",
      "בוצר-מתנה",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/Batches(Massive_gallery)%2Fbatch31%2FCopy%20of%20batches%20background.png?alt=media&token=7b4c6df4-417c-444a-96f7-6ff482685097",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2Frand%2Fdfsfewf3234f3.jpeg?alt=media&token=203fd3c9-5a46-4329-874c-ff10485fa2d6",
    ],
    fullDesc:
      '<h2>תכולת המארז:</h2><ul><li>קרש חיתוך גדול עם חריטה</li><li>סכין שפכטל לחיתוך בצק עם חריטה</li><li>מארוך מקצועי</li></ul><p><br></p><h2>גדלים ומידות:</h2><ul><li>מידות הקרש: 40x30x2 ס"מ</li><li>סכין שפכטל: 8x15 ס"מ</li><li>מארוך: אורך 45 ס"מ</li><li><br></li></ul><h2>פרטים על המארז:</h2><p>מארז לאופים עם חריטה הכולל קרש חיתוך גדול עם חריטה, שפכטל לבצק עם חריטה ומערוך.</p><p>מארז חריטה 3 חלקים לחובבי הבצקים והאפייה הכולל: קרש חיתוך, סכין שפכטל לחיתוך בצק ומריחת קרמים עם חריטה ומערוך מקצועי (ללא חריטה).</p><p>החריטה על הקרש מגיעה בגוון שחור-חום כהה כתלות בשטח החריטה.</p><p>החריטה על הסכין שפכל מגיע בגוון שחור.</p><p>מתנה מושלמת לכל חובב אפייה או בעל מקצוע מהתחום.</p>',
    bestSeller: false,
  },
  {
    renderOrder: "3",
    types: [],
    multiDesign: false,
    designImage: {
      desktop:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Fbamboo_small_widget.jpeg?alt=media&token=9dd03b71-c423-4250-9903-5d5a5fc55fab",
      mobile:
        "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productGalley%20ARCOS%2Fbamboo_small_widget.jpeg?alt=media&token=9dd03b71-c423-4250-9903-5d5a5fc55fab",
    },
    type: "bamboo_small",
    content: "",
    bestSeller: false,
    category: "butcher",
    shortName: "קרש חיתוך במבוק בינוני",
    tomixProduct: false,
    shouldDesign: true,
    staging: false,
    price: 199,
    stock: 9,
    image: "https://assets.nameitonsteel.com/products/bamboo_small/12.webp",
    thumbImage:
      "https://assets.nameitonsteel.com/products/bamboo_small/12.webp",
    name: 'קרש חיתוך עם חריטה מעץ במבוק באורך 35 ס"מ',
    details:
      "קרש חיתוך עם הקדשה בחריטה אישית מעץ במבוק. מידת הקרש חיתוך עם חריטה 35/25/1.5",
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch21%2FWhatsApp%20Image%202021-10-18%20at%2016.46.13%20(1).jpeg?alt=media&token=5f1d8701-bfd9-4a7a-b27c-0ab331e6ff27",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch21%2FWhatsApp%20Image%202021-10-18%20at%2016.46.15%20(1).jpeg?alt=media&token=cc70fca4-76dd-457a-8b68-bb5c9c82013c",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch14%2FWhatsApp%20Image%202021-08-29%20at%2016.17.49.jpeg?alt=media&token=ea74aa5a-a712-4dff-8231-190396342579",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-25%20at%2016.21.21%20(3).jpeg?alt=media&token=d2cbad6a-86bb-4733-8f57-10de4be58199",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch22%2FWhatsApp%20Image%202021-10-24%20at%2014.19.04.jpeg?alt=media&token=9d76b07c-f15d-4237-9017-58214c869b9a",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch23%2FWhatsApp%20Image%202021-11-02%20at%2016.55.16.jpeg?alt=media&token=90c916bc-0163-4290-b05d-a095a0bc7775",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch23%2FWhatsApp%20Image%202021-11-02%20at%2016.55.20.jpeg?alt=media&token=e26c1e4d-66cf-4cd8-a117-7420eca62549",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch23%2FWhatsApp%20Image%202021-11-02%20at%2016.55.17.jpeg?alt=media&token=a2aa3930-6899-40dd-a658-370c012b3006",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch25%2FWhatsApp%20Image%202021-11-14%20at%2011.07.33%20(3).jpeg?alt=media&token=76e15c41-082e-41a6-b796-4aafb1596a76",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch25%2FWhatsApp%20Image%202021-11-14%20at%2011.09.00%20(5).jpeg?alt=media&token=d04e4041-2070-4ea2-beda-640376ee1694",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch26%2FWhatsApp%20Image%202021-11-22%20at%2016.13.07%20(4).jpeg?alt=media&token=e5be881d-43c5-48c4-8823-5e5c1979fef3",
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/Batches(Massive_gallery)%2FBatch27%2FWhatsApp%20Image%202021-11-30%20at%2015.40.26%20(13).jpeg?alt=media&token=2f7daa00-1a52-4ebb-92ef-de0eec391fa5",
    ],
    tags: [
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "מתנה-למפקד",
      "birthday-gifts",
      "בוצר-מתנה",
      "משפטים-לחריטה-על-בוצר",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
    fullDesc:
      "<h2>מידות ומאפיינים:</h2><ul><li>גודל: 35x25x1.5 ס\"מ</li><li>תעלה לניקוז נוזלים בקצוות הבוצ'ר</li></ul><p><br></p><h2>על קרש החיתוך בוצ'ר עם חריטה:</h2><p>קרש חיתוך עם הקדשה בחריטה אישית מעץ במבוק - מגיע עם מסילה לניקוז הנוזלים בקצוות הבוצ'ר.</p><p>החריטה על קרש החיתוך מגיעה בגוון חום כהה-שחור ונעשית על ידי מכונת לייזר.</p><p>עיצוב קרש החיתוך נעשה בקלות ובמהירות באתר - ניתן לחרוט טקסטים בכל השפות ולהוסיף לוגואים ממבחר הלוגואים באתר.</p><p>המחיר כולל חריטת לייזר ומשלוח עד דלת הבית.</p>",
  },
  {
    shouldDesign: false,
    type: "beroxSharpener",
    price: 79,
    image:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/MainProductPictures_superCompressed%2Fsharpener_berox.jpg?alt=media&token=6b894a58-6c7b-48e9-8fe6-02201b40c974",
    staging: false,
    renderOrder: 3,
    stock: 11,
    name: "משחיז סכינים מקצועי תלת שלבי\n",
    details: "משחיז סכינים ביתי תלת שלבי לשמירה על חדות הסכין.\n",
    productImages: [
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery2%2Fsharpenerpic1.jpeg?alt=media&token=a5c020e1-27a3-48ad-865f-b71167f2645d",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery2%2Fsharpenerpic2.jpeg?alt=media&token=fa44bc90-c0a3-47ef-8eb3-2583fe0072fd",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/productsGallery2%2Fsharpenerpic3.jpeg?alt=media&token=ba8dfbbc-69d8-4d22-a05e-cdbbd81d2615",
    ],
    types: [],
    multiDesign: false,
    bestSeller: false,
    designImage: {
      desktop: "",
      mobile: "",
    },
    shortName: "",
    tomixProduct: false,
    content: "",
    thumbImage:
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/MainProductPictures_superCompressed%2Fsharpener_berox.jpg?alt=media&token=6b894a58-6c7b-48e9-8fe6-02201b40c974",
    tags: [
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "אביזרים-למטבח",
      "market.html",
      "סכיני-שף-עם-חריטה",
      "סכיני-בשר-וסכיני-קצבים-עם-חריטה",
      "סכינים-וקרשי-חיתוך-עם-חריטה",
      "מתנה-למפקד",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
    category: "complementary",
    fullDesc:
      "<p>משחיז סכינים תלת שלבי רב שימושי הכולל שלב קרמיקה, שלב פחמן ושלב יהלום. </p><p>השחזת היהלום מתאימה לסכין קהה, השחזת פחמן משמשת לתחזוקת הלהב, והשחזת הקרמיקה מעדנת את הלהב ומסירה פגמים. </p><p>המשחיז מגיע עם ידית מובנת אשר מקלה על פעולת השחזת הסכין.</p>",
  },
  {
    shouldDesign: false,
    image:
      "https://assets.nameitonsteel.com/products/birkat_habait/mainImage.webp",
    renderOrder: 3,
    types: [],
    multiDesign: false,
    designImage: {
      desktop: "",
      mobile: "",
    },
    type: "birkat_habait",
    content: "",
    productImages: [],
    thumbImage:
      "https://assets.nameitonsteel.com/products/birkat_habait/ThumbImage.webp",
    price: 199,
    bestSeller: false,
    name: "שלט ברכת הבית מעוצבת לתלייה בחריטה אישית על פלטת עץ",
    details:
      "מתנה לבית חדש - שלט ברכת הבית מעוצבת לתלייה בחריטה אישית על פלטת עץ",
    category: "",
    shortName: "ברכת הבית",
    stock: 11,
    tomixProduct: false,
    staging: false,
    upsell: true,
    fullDesc:
      '<p>שלט ברכת הבית מעוצב לתלייה בחריטה אישית על פלטת עץ גדולה, במידות 53/30 ס"מ.</p><p>שלט ברכת הבית מיוחד בצורה טבעית, ייחודי ובחריטה אישית. </p><p>מתנה לחנוכת בית לתלייה על הקיר.</p><p>שלט ברכת הבית מגיע עם חור ייחודי וחוט לתליה.</p>',
    tags: [
      "מתנה-לראש-השנה",
      "מתנות-לגבר",
      "מתנות-ליום-הולדת-לגבר",
      "market.html",
      "מתנה-למפקד",
      "ברכת-העסק-מעוצבת",
      "ברכת-העסק-מתנה",
      "חריטה-על-עץ",
      "בוצר-מתנה",
      "מתנה-לעובדים",
      "birthday-gifts",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
      "other-with-engrave",
    ],
  },

  {
    renderOrder: 3,
    multiDesign: true,
    hasButcher: true,
    type: "c_4steakKnives",
    price: 479,
    category: "package",
    staging: false,
    shouldDesign: true,
    bestSeller: false,
    designImage: {
      desktop: "",
      mobile: "",
    },
    shortName: "",
    tomixProduct: false,
    content: "",
    tags: [
      "מתנות-ליום-הולדת-לגבר",
      "מתנה-לראש-השנה",
      "אביזרים-למטבח",
      "מתנות-לגבר",
      "market.html",
      "מתנה-למפקד",
      "birthday-gifts",
      "בוצר-מתנה",
      "מתנות-לחג",
      "מתנות-לחינה",
      "מתנות-בעיצוב-אישי",
      "מתנות-עם-חריטה",
      "מתנות-לחנוכת-בית",
      "מתנות-ליום-נישואים",
    ],
    image:
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/mainImages%2F%D7%AA%D7%9E%D7%95%D7%A0%D7%94%20%D7%A8%D7%90%D7%A9%D7%99%D7%AA%20%D7%A1%D7%98%D7%99%D7%99%D7%A7%20%D7%95%D7%A4%D7%9C%D7%A4%D7%9C%20%D7%9E%D7%9C%D7%97%20(1).png?alt=media&token=cbf9aa7e-7267-49af-9e63-c1bcf0bbf370",
    productImages: [
      "https://storage.nameitonsteel.com/productImages/c_4steakKnives/5.webp",
      "https://storage.nameitonsteel.com/productImages/c_4steakKnives/6.webp",
      "https://firebasestorage.googleapis.com/v0/b/nameitonsteelwebsite.appspot.com/o/Gallery_Project_2021%2FBatch26%2FWhatsApp%20Image%202021-11-22%20at%2016.13.07%20(9).jpeg?alt=media&token=bb0e544e-2b99-424a-a7a0-280328ea6521",
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/mainImages%2F%D7%AA%D7%9E%D7%95%D7%A0%D7%94%20%D7%A8%D7%90%D7%A9%D7%99%D7%AA%20%D7%A1%D7%98%D7%99%D7%99%D7%A7%20%D7%95%D7%A4%D7%9C%D7%A4%D7%9C%20%D7%9E%D7%9C%D7%97%20(1).png?alt=media&token=cbf9aa7e-7267-49af-9e63-c1bcf0bbf370",
    ],
    thumbImage:
      "https://firebasestorage.googleapis.com/v0/b/assets.nameitonsteel.com/o/mainImages%2F%D7%AA%D7%9E%D7%95%D7%A0%D7%94%20%D7%A8%D7%90%D7%A9%D7%99%D7%AA%20%D7%A1%D7%98%D7%99%D7%99%D7%A7%20%D7%95%D7%A4%D7%9C%D7%A4%D7%9C%20%D7%9E%D7%9C%D7%97%20(1).png?alt=media&token=cbf9aa7e-7267-49af-9e63-c1bcf0bbf370",
    name: "בוצ'ר /קרש חיתוך וסכיני סטייק עם חריטה",
    details:
      "מארז מתנה הכולל בוצ'ר עם חריטה במידה 45/30/3 ס\"מ וסט סכיני סטייק עם חריטת לייזר",
    types: ["steak_knife", "sisam_gumot"],
    fullDesc:
      "<h2>תכולת המארז:</h2><ul><li>בוצ'ר גדול לבשר עם חריטה - כולל תעלה וגומות למלח פלפל</li><li>סט 4 סכיני סטייק עם חריטה</li></ul><p><br></p><h2>גדלים ומידות:</h2><ul><li>מידות הבוצ'ר: 45x30x3 ס\"מ</li><li>סכיני סטייק: להב 12 ס\"מ</li></ul><p><br></p><h2>פרטים על המארז:</h2><p>סכיני סטייק איכותיים ובוצ׳ר עם חריטה, מתנה מושלמת לאוהבי בשר.</p><p>המארז כולל בוצ'ר עם חריטה וסט 4 סכיני סטייק גדולות עם חריטה בעלות להב באורך 12 ס\"מ - החריטה זהה על כל הסכינים.</p><p>הסכינים בעלות שיניים אשר מאפשרות חיתוך קל ונוח לבשר.</p><p>הבוצ'ר מגיע עם תעלת ניקוז אשר אוגרת נוזלים בשימוש עם בשרים ושומרת על עבודה נקיה וסטרילית.</p><p>הבוצ'ר בעל שתי גומות המיועדות למלח ופלפל.</p><p>החריטה על הבוצ'ר בגוון חום-שחור כתלות בחלק העץ והחריטה על הסכין בצבע שחור ואינה ניתנת להסרה.</p>",
    stock: 1,
  },
];

window.addEventListener("load", () => {
  // Render the product cards inside #placeholder
});

const dialog = document.querySelector("#product-dialog");

const getProductHTMLCard = (product) => {
  const template = `Write your card template instead of me`;

  // Insert the card template into a new HTML Div element.
  // Add your click listener on the new HTML Div Element (HandleProductClick)
  // return your element with the template as a inner html
};

const getCloseModalHTMLButton = () => {
  // Create a new HTML Button element
  // Add the text of the button inside innerText property
  // Listen to click -> close dialog when clicked
  // return your new close button
};

const handleProductClick = (product) => {
  // clean up existings children by doing dialog.innertHTML=""
  // Render the extended clicked product view inside the dialog.
  // render the close button inside the dialog so it could be closed
  // show the dialog with showModal() method
};
